### ISSUE TITLE
NLog Mapping To Custom Properties

### ISSUE THREAD

**Issue by finprod** [mperdeck/jsnlog#104]
Hi,

let's say I have some kind of structured logging on the client side:

`JL("logger1").warn({"action": "name_bla", "durationMs": 600});`

If I understand it correctly, I can write the whole object as single string only. On the server side I use NLog and would like to extract the properties "action" and "durationMs" to be able to save them to my db into separate columns. It would be nice if it worked with NLog syntax, e.g. 

`<parameter name="@action" layout="${jsnlog-action}" />` etc.

Then I could just insert all the data into the db (with the following NLog config):

`<target name="database" xsi:type="Database"  commandText="INSERT INTO [Log] ([Action], [DurationMs]) VALUES (@action, @durationMs)`

Regards,
Cezary

**Comment by jonathancounihan-sage** [comment]
+1

**Comment by mperdeck** [comment]
That sounds like an interesting idea. It would work too if you logged a json object as a string on the server. I guess you would have to take care to only log json objects that have fields that are defined in the NLog config.

However, to me this is not related to JSNLog. JSNLog lets you log on the client, and it provides an endpoint on the server that passes log messages onto Common.Logging. This then talks to whatever server side logging package you configured in your web.config. That is, JSNLog has no idea that NLog is being used.

You might want to create your own NLog target that does what you described (if there isn't one already). Or consider Serilog, a logging package that lets you store json objects in a NoSQL
