### ISSUE TITLE
Consider LibLog instead

### ISSUE THREAD

**Issue by dazinator** [mperdeck/jsnlog#107]
Consider switching to [LibLog](https://github.com/damianh/LibLog) and removing Common.Logging.

LibLog does not force any dependencies to consumers, as its a c# code file compiled with your own assembly. Where as Common.Logging forces others to adopt that dependency. Not a major thing but nicer imho

**Comment by mperdeck** [comment]
Thanks for the suggestion. Just had a look at LibLog. The fact that it figures out what server side logging library is being used is very useful. 

However, it doesn't support Elmah, which is very popular (over 12000 downloads for the JSNLog.Elmah package). If/when that support becomes available and I get more time, it is certainly something I'd want to have a look at again.
