### ISSUE TITLE
.Net 4.0 vs. 4.5.1

### ISSUE THREAD

**Issue by nlinnett** [mperdeck/jsnlog#110]
Hi there,

What version of jsnlog support .Net 4.0 instead of requiring 4.5.1?

I'm looking at setting up a basic logging framework for work, and don't want to have to update versions if I don't need to.

Thanks, Nigel

**Comment by mperdeck** [comment]
The last version of JSNLog that supported .Net 4.0 was
http://www.nuget.org/packages/JSNLog/2.17.4

**Comment by nlinnett** [comment]
Thanks very much
