### ISSUE TITLE
Strong name version of JsnLog

### ISSUE THREAD

**Issue by muffadal53** [mperdeck/jsnlog#111]
I need strong name version of JSNLog assembly for our project. How can I obtain that?

**Comment by mperdeck** [comment]
Apologies for the late reply.

I guess you want to put the JSNLog assembly in the GAC. I am trying to understand the business reason behind this. Why do you need a strong name version of JSNLog?

**Comment by muffadal53** [comment]
The reason I need strong name version of JSNLog is because we digitally sign all our assemblies. So, to successfully sign our assemblies, we need all reference assemblies to be digitally signed. Hence, we need strong name version of it. For your information all the other Nuget packages which we are using in our project are already strong name. Hope this clarifies.

**Comment by mperdeck** [comment]
The JSNLog assembly now has a strong name. Just released this (version 2.19.2).
