### ISSUE TITLE
Change log and version number

### ISSUE THREAD

**Issue by sergkr** [mperdeck/jsnlog#114]
Is there any sort of change log or version history for this project (besides going through commit history)? I was going through all the dependencies in our project and saw that this library had some updates recently, but I couldn't find a quick way to see what was changed.

On a related note, the emitted files jsnlog.js and jsnlog.min.js have no comment header at the top to identify the version number. I dropped these files into our project a couple months ago, but I now have no way of identifying what version they correspond to. (We're not using a package manager of any sort for this particular project.) I would recommend including a comment header with at least a project URL, version number, author, and license.

**Comment by mperdeck** [comment]
I'm sorry, there is no change log apart from the commit history.

Re. adding a comment header to jsnlog.js and jsnlog.min.js - that's a great idea. I've done this now for the latest release (2.19.2, just released).
