### ISSUE TITLE
When the application is behind a proxy/load balancer server the clientIP attribute contains the proxy server IP and not the end client IP

### ISSUE THREAD

**Issue by chikkannam** [mperdeck/jsnlog#115]
Can the GetUserIp method first check the HTTP_X_FORWARDED_FOR server variable, if found to be null or empty, then  fetch IP from UserHostAddress? Something like below

(string.IsNullOrEmpty(HttpContext.Current.Request.ServerVariables["HTTP_X_FORWARDED_FOR"]) ? HttpContext.Current.Request.UserHostAddress : HttpContext.Current.Request.ServerVariables["HTTP_X_FORWARDED_FOR"]);

**Comment by mperdeck** [comment]
Sounds like a good idea. 

I am not behind a load balancer. I also have little time. Could you do a pull request (ensuring it works both behind your load balancer and when not behind a load balancer)?

**Comment by chikkannam** [comment]
I have created a pull request. The code has been tested locally behind/without a load balancer.
