### ISSUE TITLE
Can't install *JSNLog.NLog* version 2.20.0 in Visual Studio 2012

### ISSUE THREAD

**Issue by kenny-evitt** [mperdeck/jsnlog#119]
On the project home page, instructions for "Visual Studio 2013 or older" state:

> These packages contain dependencies for both ASP.NET 4.x and ASP.NET Core. However, versions below 2.8.60318.667 of the NuGet Package Manager installed in Visual Studio do not support this.

This seems to imply that packages should be able to be installed with NuGet Package Manager version 2.8.60318.667 or newer.

In the NuGet Package Manager Console in VS, I ran `Install-Package JSNLog.NLog`; the output:

```
Attempting to resolve dependency 'Common.Logging (≥ 3.3.1)'.
Attempting to resolve dependency 'Common.Logging.Core (≥ 3.3.1)'.
Attempting to resolve dependency 'Common.Logging.NLog20 (≥ 3.3.1)'.
Attempting to resolve dependency 'NLog (≥ 2.0.0)'.
Attempting to resolve dependency 'JSNLog (≥ 2.20.0)'.
Install-Package : The 'JSNLog 2.20.0' package requires NuGet client version '3.4' or above, but the current NuGet version is '2.8.60318.667'.At line:1 char:1
+ Install-Package JSNLog.NLog
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], NuGetVersionNotSatisfiedException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
```

Is the home page info obsolete?

What's the latest version that I should be able to install successfully?

**Comment by mperdeck** [comment]
I suspect that the home page is wrong, and that it should have said that versions 2.8.60318.667  and older are obsolete (that is, 2.8.60318.667  is obsolete as well).

Thanks for pointing this out. I'll fix this in the next release.

**Comment by kenny-evitt** [comment]
@mperdeck Thanks! If 2.8.60318.667 is in fact obsolete then JSNLog cannot be installed in Visual Studio 2012, at least as-of today because 2.8.60318.667 is the latest version of NuGet available for it. That would also be worth mentioning given that I am effectively an existence proof that some people are stuck on versions of Visual Studio that old.

**Comment by mperdeck** [comment]
I understand you can't upgrade from Visual Studio 2012. Why is this?
(I'm trying to understand the impact of no longer supporting older versions of Visual Studio)

**Comment by kenny-evitt** [comment]
@mperdeck Sorry for the confusion. I'm not stuck in the sense that it's *impossible* for me to upgrade Visual Studio. But it would be a (potentially) significant project for me to do so so I am *practically* stuck on an older version for the time being.

I almost certainly can upgrade. But I need to buy a license for at least the Professional edition according to Microsoft's licensing terms. I could imagine some people rationally deciding not to do so.

Visual Studio 2012 still works for me so, were this the only reason I had for upgrading, $500 would be a pretty steep price to pay!

The people likely to be most significantly affected by needing to upgrade would be people in small "enterprise" organizations or anyone otherwise inelligble to use the free Visual Studio editions.

Personally, I want to upgrade, and for several reasons, so I don't think you need to support older versions.
