### ISSUE TITLE
JNSLOG WITH ASPNET CORE AND SERILOG BUG ????

### ISSUE THREAD

**Issue by mondraker** [mperdeck/jsnlog#121]
What happend ? , my log write this : 
08:30:09 [Fatal] [12345] [MONDRAKER] [mondr_000\MONDRAKER] [23] [ClientRoot] "log message"
08:30:09 [Fatal] [12345] [MONDRAKER] [mondr_000\MONDRAKER] [24] [onerrorLogger] [[[]], [[]], [[]], [[[[]], [[]], [[]], [[]], [[]]]]]
08:30:39 [Fatal] [12345] [MONDRAKER] [mondr_000\MONDRAKER] [23] [ClientRoot] "prueba"

This is from this code : 
JL("onerrorLogger").fatalException({
            "msg": "Uncaught Exception",
            "errorMsg": errorMsg, "url": url,
            "line number": lineNumber, "column": column
        }, errorObj);

What happend with this trace: [[[]], [[]], [[]], [[[[]], [[]], [[]], [[]], [[]]]]]

Thanks so much .

**Comment by mperdeck** [comment]
I have absolutely no idea what happened, mainly because there is no way I can find out from what you told me.

Please create a small test application that reproduces the problem, put it on Github and tell me where to find it. That will allow me to reproduce the issue at my end and possibly find a solution.

**Comment by mondraker** [comment]
https://github.com/mondraker/JSNLOGREPO

Thanks.

**Comment by pandazzurro** [comment]
This is not a bug but an serialization error.
I have this problem with AzureTableSink and change my angular2 service.
I must insert this chars \' instead of ".
This is my example:
https://github.com/pandazzurro/LogClientSideFull/blob/master/Angular/LogClientSide/src/app/jslogger.service.ts#L15
