### ISSUE TITLE
Jsnlog does not work in Visual studio 2013

### ISSUE THREAD

**Issue by pawepaw** [mperdeck/jsnlog#122]
When i tried to restore nuget packages in visual studio 2013 i got:
```Error 1 NuGet Package restore failed for project Test: The 'JSNLog 2.19.2' package requires NuGet client version '3.4' or above, but the current NuGet version is '2.12.0.817'.. ```

Nuget 2.12 is the newest version which you can install to Visual studio 2013. Anyone know how to fix it and use jsnlog in VS 2013?

**Comment by mperdeck** [comment]
I just released a new version 2.20.1 which hopefully fixes this problem.
