### ISSUE TITLE
Using JSNLog with Angular 2

### ISSUE THREAD

**Issue by molyviatisl** [mperdeck/jsnlog#123]
I am having trouble getting JsNlog to work with Angular 2 (latest full release).  I install JsNlog into my project (empty client web application in Visual Studio 2015) via npm.  I have tried to set it up in a service but I get the error "XHR error (403 Forbidden) loading".  
My service code:
import { Injectable, Component } from '@angular/core';
import JL from 'jsnlog';

@Injectable()

export class JSLoggerService
{ 
    constructor()
    {

```
}

log(msg: string)
{

    JL('Angular').trace(msg);
}

debug(msg: string)
{
    JL('Angular').debug(msg);
}

info(msg: string)
{
    JL('Angular').info(msg);
}

warn(msg: string)
{
    JL('Angular').warn(msg);
}

error(msg: string)
{
    JL('Angular').error(msg);
}
```

}

Please help

**Comment by mperdeck** [comment]
Could you please create a small test application that reproduces this problem, put it on Github and tell me where to find it. That allows me to easily reproduce the problem and maybe fix it.

**Comment by molyviatisl** [comment]
[Angular 2 jsnlog.zip](https://github.com/mperdeck/jsnlog/files/548306/Angular.2.jsnlog.zip)

Hi,

Attached is a very cut down version of my project that illustrates the issue (Sorry, I wasn't sure how to put it on Github).  Please let me know what I am doing wrong.

**Comment by molyviatisl** [comment]
Hi Matthew,

Any news on this?  Please let me know.

Thanks

**Comment by pandazzurro** [comment]
This is my error when use this code: `import JL from 'jsnlog';`
'jsnlog' is not a known element:
1. If 'jsnlog' is an Angular component, then verify that it is part of this module.
2. If 'jsnlog' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.

**Comment by pandazzurro** [comment]
Hi @molyviatisl 
I have created a project with angular2.
I have created one component for JSNLog with your JSNLogService.
I test JSNLog with two different backend:
1. Asp net core
2. Asp net 4.6

I write log with Serilog and Azure Table Storage sink.
I was able to try it and it's working.

@molyviatisl CORS or defaultAjaxUrl is your problem?

If @mperdeck want you can use it as an example.

**Comment by molyviatisl** [comment]
Thanks @pandazzurro  I will have a look and try to get it working.

**Comment by mperdeck** [comment]
I finally got round to adding a page to jsnlog.com describing how to add JSNLog to an Angular 2+ app:
http://jsnlog.com/Documentation/HowTo/Angular2Logging

**Comment by aviran05** [comment]
@pandazzurro  Hi, 
can i have the working demo for .net 4.6?
thanks.

**Comment by pandazzurro** [comment]
You should use the last version of the guide.
You Can find my example: https://github.com/pandazzurro/LogClientSideFull/blob/master/Angular/LogClientSide/src/app/jsnlog/jsnlog.component.ts

**Comment by aviran05** [comment]
Thank you very much

**Comment by pandazzurro** [comment]
Sorry, 4.6 is on this repo:

https://github.com/pandazzurro/LogClientSide/tree/master/Backend/LogClientSide.FullFramework.JSNlog
