### ISSUE TITLE
Incompatibility between Dotnet core, JSNLog and Serilog

### ISSUE THREAD

**Issue by hugoterelle** [mperdeck/jsnlog#125]
Hi,

I try to use JSNLog in structured mode with Serilog as explained in the documentation: 
http://jsnlog.com/Documentation/HowTo/StructuredLogging

I have the following code in the startup.cs 

```
var jsnlogConfiguration = new JsnlogConfiguration 
{
serverSideMessageFormat = "[UserIp: %userHostAddress], [Url: %url], [Browser: %userAgent] %message"
};

app.UseApplicationInsightsRequestTelemetry()
    .UseApplicationInsightsExceptionTelemetry()
    .UseStaticFiles()
    .UseMvc(routes => { routes.MapRoute("default", "{controller=Home}/{action=Index}/{id?}"); })
    .UseJSNLog(new LoggingAdapter(loggerFactory), jsnlogConfiguration); // Javascript logging
```

And in my project.json, I have the following configuration:

```
 "JSNLog.AspNetCore": "2.20.1",
    "Serilog": "2.3.0",
    "Serilog.Extensions.Logging": "1.2.0",
    "Serilog.Sinks.File": "3.1.0",
    "Serilog.Sinks.RollingFile": "3.1.0",
    "Serilog.Sinks.Literate": "2.0.0",
    "Serilog.Sinks.AzureTableStorage": "2.0.0",
    "Serilog.Settings.Configuration": "2.1.0",
    "Serilog.Enrichers.Environment": "2.1.0",
    "Serilog.Enrichers.Thread": "2.0.0"

```

When I try to add 
`"JSNLog.Serilog": "2.20.1"` in the project.json file, I receive the following errors at compile time:

`The type or namespace name 'LoggingAdapter' could not be found (are you missing a using directive or an assembly reference?)`

Any idea?

Thanks
Hugo Terelle

**Comment by mperdeck** [comment]
It looks like you're using .Net Core. However, the JSNLog.Serilog package is only for use with ASP.NET 4.x.

In the ASP.NET 4.x version of JSNLog, JSNLog uses the Common.Logging package to talk to the actual logging package (in your case, that's serilog). The JSNLog.Serilog package is a wrapper that loads and installs the Serilog adapter for Common.Logging.

 However, in ASP.NET Core, Common.Logging is not supported. Instead, all logging is done through the ILoggerFactory interface (which decouples the code that does the logging from the actual logging package, similar to what Common.Logging does in 4.x).

Google knows much more about ILoggerFactory.
To see how to tie this in with JSNLog, see
http://jsnlog.com/Documentation/DownloadInstall/ForAspNetCore
