### ISSUE TITLE
License link is broken on http://jsnlog.com/

### ISSUE THREAD

**Issue by SamPlusPlus** [mperdeck/jsnlog#126]
![image](https://cloud.githubusercontent.com/assets/740393/19652290/408177ac-99de-11e6-9b58-b8c5c1447c3e.png)

Points to https://github.com/mperdeck/jsnlog/blob/master/LICENSE instead of https://github.com/mperdeck/jsnlog/blob/master/LICENSE.md

**Comment by mperdeck** [comment]
Thanks for the bug report! It will be fixed next time I update the site.
