### ISSUE TITLE
JSNlog.log4net - How to custom log

### ISSUE THREAD

**Issue by dvign72** [mperdeck/jsnlog#127]
Hi,
i have a c# project with log4net ( for the c# code log ). I have customized this log with new fields.

Now, i need to add a log for Front-End ( JS ). 
I try JSNLog.log4net and it work, but I need to add some of the log4net customized fields for more information.

How can I do?

Bye
Davide

**Comment by mperdeck** [comment]
Have a look at
http://jsnlog.com/Documentation/HowTo/RequestIds#log4net

This shows how to add a customized field to your Log4Net log with the request id. Maybe you can use the same method to your own fields.
