### ISSUE TITLE
Why are script tags set in this order?

### ISSUE THREAD

**Issue by voroninp** [mperdeck/jsnlog#128]
This is how generated tags look like:

```html
<script type="text/javascript">
//<![CDATA[
var __jsnlog_configure = function (JL) {
JL.setOptions({"clientIP": "::1",
"requestId": "80000412-0002-f700-b63f-84710c7967bb",
"enabled": true,
"maxMessages": 2147483647});
}; try { __jsnlog_configure(JL); } catch(e) {};
//]]>
</script>
<script type="text/javascript" src="/Scripts/jsnlog.min.js"></script>
```

As `jsnlog.js`  tag is placed after the generated script the first invocation of the script goes to `catch(e)` because `JL` is not defined yet.

What is the purpose of this tag sequence?

**Comment by mperdeck** [comment]
Please read
http://jsnlog.com/Documentation/JSNLogJs/ConfigureFunction

You're right that in the most common scenario, it will always throw an exception (that then gets caught). But in some scenarios, jsnlog gets loaded first. Anyway, the link above gives more details.
