### ISSUE TITLE
All trace shown as Exceptions

### ISSUE THREAD

**Issue by charettedavid** [mperdeck/jsnlog#130]
When i log using JL().info("log message"); in ElLMAH console it is shown as " Exceptions " is there a way to pass the same error level all the way to SQL database?

Thank you

**Comment by mperdeck** [comment]
That's a good question. Let me give you some background.

1) JSNLog talks to the logging package (in your case, Elmah), via a Common.Logging adapter. For Elmah, I wrote the adapter myself. It is at:
https://github.com/mperdeck/Common.Logging.Elmah.v2
https://www.nuget.org/packages/JSNLog.Elmah/

2) This is quite a while ago, but I can remember that I couldn't figure out how to log something through Elmah other than through an exception. But then, I am not experienced with Elmah at all (I tend to use Log4Net and NLog). 

So to answer your question: 1) no, JSNLog doesn't give you some option to do this out of the box, and 2) I would definitely be receptive to a pull request to improve the adapter.

**Comment by charettedavid** [comment]
Thank you for your reply. i'll take a look this week if i can free some
time.

thanks

2016-11-19 5:38 GMT-05:00 mperdeck <notifications@github.com>:
