### ISSUE TITLE
JSNLog.NLog - Common.Logging 

### ISSUE THREAD

**Issue by 304NotModified** [mperdeck/jsnlog#132]
Why is JSNLog.NLog dependent of the Common.Logging packages and not NLog itself?

I think Common.Logging is great for library authors, so that end users could choose which logging framework to use (NLog, Log4net etc).

But if someone already chooses for NLog, it's strange that we need (also) the Common.Logging package.

**Comment by mperdeck** [comment]
It doesn't use NLog directly.

JSNLog uses Common.Logging to talk to the server side logging package. That made it easy for me to support multiple server side logging packages. 

JSNLog.NLog is simply a convenience package that installs both JSNLog itself and the Common.Logging adapter for NLog, which is Common.Logging.NLog20. 

Common.Logging.NLog20 in turn installs NLog itself.

**Comment by 304NotModified** [comment]
Well it's less convenient for end-users ;)

Cannot recommend this library to others due to the extra needed package (and maintenance for end-users)
