### ISSUE TITLE
CSP compliant/supported?

### ISSUE THREAD

**Issue by 304NotModified** [mperdeck/jsnlog#133]
Is this library CPS (Content Security Policy Reference) compliant/supported? (= with 'unsafe-inline' and 'unsafe-eval'  disabled).

I could only work if we create an external script file. (for CPS 1) and I'm not sure if we could put `@Html.Raw(JSNLog.JavascriptLogging.Configure())` in a external file (view)

**Comment by mperdeck** [comment]
Sorry for the extremely late response. I've now added a page to the jsnlog.com site that addresses CSP:
http://jsnlog.com/Documentation/HowTo/ContentSecurityPolicy

Essentially, JSNLog doesn't do eval, so no need to use unsafe-eval. However, the Configure method generates inline JavaScript code, so you'll need to use one of the other ways to load jsnlog.js, and do any configuration (which is optional) in your JavaScript.
http://jsnlog.com/Documentation/HowTo/LoadingJsFile
