### ISSUE TITLE
ASP .NET Core MVC

### ISSUE THREAD

**Issue by pandazzurro** [mperdeck/jsnlog#137]
I found this error on startup application:
**System.InvalidOperationException: Can not find compilation library location for package 'JSNLog'
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()**
I have create default ASP .NET Core application with VS2017. 
I insert "JSNLog.AspNetCore" Nuget packages (v 2.22.1).
I insert code in startup.cs.
`` var jsnlogConfiguration = new JsnlogConfiguration();
app.UseJSNLog(new LoggingAdapter(loggerFactory), jsnlogConfiguration);``

An example: https://github.com/pandazzurro/LogClientSideFull/tree/master/ASP.NET%20Core
@mperdeck Do you have some idea?

**Comment by pandazzurro** [comment]
Recompiling only .netstandard 1.6 and reference projects, it works!

**Comment by C1aud3** [comment]
I'm also having the same issue.  A new version of the NuGet package that fixes this would be greatly appreciated.  Thanks!

**Comment by GITHuHo** [comment]
Same issue here using netcoreapp1.1 and SDK version 1.0.1. Tried to create a new version of JSNLog.AspNetCore (using dotnet migrate to convert to csproj style), but to no avail. A new NuGet version for netcoreapp1.1 would be highly appreciated. Thanks!

**Comment by mperdeck** [comment]
I finally got it to work with .Net CORE again. Just released version 2.23.0 which works with version 1 of CORE.

**Comment by C1aud3** [comment]
Awesome!  Will give it a try tomorrow.  Thanks!!

**Comment by jasselin** [comment]
Would it be possible to add net46 as a target framework for the csproj? I can't access any of the ASP.NET Core stuff in Startup.cs, but it works fine with net452.
