### ISSUE TITLE
Allow to set LoggingAdapter without configuration

### ISSUE THREAD

**Issue by hzahradnik** [mperdeck/jsnlog#145]
I use JSNLog to log the client-side errors of an Angular2+ app, which should replace an old ASP.Net WebForms application, but is currently used simultaneously. The logging is built on log4net and uses an custom Appender, which gets an "log message object" and uses its fields to insert the log message into the database. 

Because of that, I need to use an custom LoggingAdapter for JSNLog to wrap the FinalLogData into an object before I can log it. Unfortunately, this means that I can not use the configuration of JSNLog within the web.config.

**Comment by mperdeck** [comment]
I don't understand what the issue is.

**Comment by hzahradnik** [comment]
We need a CustomLoggingAdapter. To use it, you have to call the `SetJsnlogConfiguration', but currently this means, that it is not possible to configure jsnlog using xml.
```
// configuration has to be in code
var config = new JSNLog.JsnlogConfiguration()
{
	consoleAppenders = [..],
	ajaxAppenders = [..],
	loggers = [..]
};

JSNLog.JavascriptLogging.SetJsnlogConfiguration(config, new CustomLoggingAdapter());
```
Is it possible, that there is a overload for `SetJsnlogConfiguration(JsnlogConfiguration jsnlogConfiguration, ILoggingAdapter loggingAdapter = null)` with only `ILoggingAdapter` as parameter or a explicit function `SetLoggingAdapter(ILoggingAdapter loggingAdapter)`?

P.S.: Sorry for the late answer, i was on vacation until yesterday.
