### ISSUE TITLE
JSNLog.AspNetCore 2.23 and 2.24 LoggingAdapter cannot be found

### ISSUE THREAD

**Issue by JanEggers** [mperdeck/jsnlog#147]
im using the .net 4.5.2 Version of JSNLog.AspNetCore.

In Version 2.22.1 everything works as expected but when updating to 2.23 or 2.24 `LoggingAdapter`  can not be found so `app.UseJSNLog(new LoggingAdapter(loggerFactory), jsnlogConfiguration);` fails.

**Comment by jwhitex** [comment]
In [this commit](https://github.com/mperdeck/jsnlog/commit/7c92435e8265313945f7f8d743fa3659739d2058) the preprocessor directives were changed to `NET452` from `NET40`. For those of use who target the full framework from an AspNetCore project, this is a problem. I'm targeting `NET461` and this still seems to fail. 

To reproduce, create a AspNetCore project that targets .Net Framework 4.61.

**Comment by mperdeck** [comment]
Thanks for your bug report. This has now been fixed in release 2.24.1 (just gone live).

**Comment by JanEggers** [comment]
thx mate have a nice weekend whats left of it
