### ISSUE TITLE
Can I route logging and errors separately?

### ISSUE THREAD

**Issue by kbandrew** [mperdeck/jsnlog#150]
I would like to log exceptions to Elmah and logs to Nlog.

**Comment by mperdeck** [comment]
Yes you can. But it will require a bit of coding on your part.

JSNLog logs entries simply by talking to Common.Logging, which then uses an adapter to write the log entries to NLog, Elmah, etc.

You would need to write your own Common.Logging adapter that does what you want to do. 

Both the NLog and Elmah adapters are open source, which should help you create your adapter:
https://github.com/net-commons/common-logging/tree/master/src
https://github.com/mperdeck/Common.Logging.Elmah.v2

**Comment by kbandrew** [comment]
Excellent thanks very much for the help.

Can you have multiple adaptors, or would it be better to write a custom adaptor that routes them to the relevant logger?

**Comment by mperdeck** [comment]
This is a question about the Common.Logging package rather than JSNLog. I suspect you can have only 1 adapter, but I never looked into this.
