### ISSUE TITLE
angular / log4net and shipping log messages to a server

### ISSUE THREAD

**Issue by figuerres** [mperdeck/jsnlog#151]
i am looking at using your package but i am not sure if the asp.net side is right.

i got the page http://jsnlog.com/Documentation/DownloadInstall#addtoyourpages

which is talking about MVC and Web forms

Our server side logic is using WebApi ,

currently i have a very simple api that i can call from log4javascript  using that libraries ajaxappender.

i was expecting something more like that.

perhaps you might want to take a look at that as an option for the server interface ? 

also i have not seen any documentation on how to configure the client app to send the log items to the server.
is your package assuming that the server domain for logging is the same as the domain of the client app ?
if it is then that is a problem for my case,  the server to log to should be a configuration option.

**Comment by figuerres** [comment]
based on the info i found i have tried to set my url and it is not working.
  JL().setOptions( {"defaultAjaxUrl": ""} );
errors on the options as not being the right type but the type that has the ajaxappender is not  exported in a way that works with angualr 4.

sorry but so far this is not looking very good to setup.

**Comment by mperdeck** [comment]
I understand your application is essentially an Angular 4 SPA that talks to a WebApi backend. And your approach is to create an additional WebApi endpoint to receive the JSNLog log requests.

If you use .Net 4.x, you may want to consider using JSNLog's OWIN support, where the JSNLog handler sits in the OWIN pipeline before MVC:
http://jsnlog.com/Documentation/DownloadInstall (see OWIN section)

If you prefer to do your own WebApi endpoint, the format of JSNLog messages is here:
http://js.jsnlog.com/Documentation/DownloadInstall

From your second message, I understand there is an error. But I didn't see enough details to reproduce the problem. If the problem persists, could you please create a small test application that reproduces the problem and put it on Github so I can work out a solution.

**Comment by figuerres** [comment]
The server package broke my server project and I had to go back to a prior check-in. 
On the client side I was trying to use your documentation to configure the Ajax appended url, I was getting an error as your set options method takes a typed parameter that does not have the property to set the url.

In short, nothing I tried worked.
