### ISSUE TITLE
Usage of sourcemaps to get the log

### ISSUE THREAD

**Issue by eberhm** [mperdeck/jsnlog#152]
Hello,

is it possible to use sourcemaps un production to get a more meaningful trace of the errors?

Thanks for the hardwork!!

**Comment by mperdeck** [comment]
I guess you mean you have a minified JavaScript file that uses JSNLog to report exceptions, there is a .map file for this minified file and JSNLog uses that .map file to create better log messages, with the correct line number, etc.

That would be really good. But I never found a way to accomplish this.
