### ISSUE TITLE
FinalLogData.ToString() has crash error

### ISSUE THREAD

**Issue by ayee-hatfield** [mperdeck/jsnlog#158]
jsnlog/jsnlog/PublicFacing/Configuration/FinalLogData.cs
Lines 24 - 26.

return string.Format(
                "FinalLogger: {0}, FinalLevel: {1}, FinalMessage: {2}, ServerSideMessageFormat: {3}, LogRequest: {{{5}}}",
FinalLogger, FinalLevel, FinalMessage, ServerSideMessageFormat, LogRequest);

The call to String.Format() has a wrong index number in the format string.
Format("FinalLogger: {0}, FinalLevel: {1}, FinalMessage: {2}, ServerSideMessageFormat: {3}, LogRequest: {{{5}}}"
...

The final index should be 4 in this case because there were only 5 items passed to Format().

Using the string concatenation operator + is always a safer way to put together strings than string.format() .

**Comment by mperdeck** [comment]
Thanks for pointing this out. I fixed it in the source code. It will go live with the next release.
