### ISSUE TITLE
JSNLog sendBatch does not exists on type JSNLogger.

### ISSUE THREAD

**Issue by fudgecakes** [mperdeck/jsnlog#162]
We are using JSNLog in an Angular 4 application.

We are using createAjaxAppender('example') function, however, we cannot call sendBatch() for some reason. Here is our code:

Import { JL } from 'jsnlog'
const appender = JL.createAjaxAppender("log example");

appender.setOptions({

  "url" : 'http://localhost:5000/test,
  "batchSize" : 20,
  //"batchTimeout" : 10000
});

JL().setOptions({
  "appenders": [appender]
});

//this throws an error because compiler says function does not exists on type JSNLogger
appender.sendBatch()

**Comment by mperdeck** [comment]
Apologies for the late reply. Have been swamped at work.

As you found out, sendBatch is not defined in the .d.ts files that provide type information for TypeScript. This is a bug and I'll fix that in about 2 weeks time when I return from overseas.

Meanwhile, this shouldn't be hard to fix at your end for now. In the jsnlog related .d.ts files, look for the JSNLogAppender interface and add the missing sendBatch definition. If you could send me a pull request, that would be great :-)

**Comment by mperdeck** [comment]
I just released 2.26.2, which fixes this issue.
