### ISSUE TITLE
Structured logging using Serilog not achievable with this library?

### ISSUE THREAD

**Issue by Etchelon** [mperdeck/jsnlog#164]
Hi,
I'm using Serilog in my netcore 2 app and I'm now trying out JSNLog.
After following the documentation I've come to the conclusion that this library doesn't allow to perform structured logging, despite what you declare in the documentation.
With structured logging I mean specifying a message template and supplying parameters, and let the logger render the message.
In fact, the client side JSNLogger has methods that accept a single parameter, either a strings or an object. Structured logging methods from Serilog, or even the built in AspnetCore ILogger, have a signature like 
`Log(string message, params object[] args)`
and you invoke them like this:
`Log("Structured log from user {User}, at time {Now}", "AppUser", DateTime.Now);`
The besides the signature of JS methods, the big problem lies in method Log(FinalLogData finalLogData) in class JSNLog.LoggingAdapter, precisely in lines 32-37:
`           switch (finalLogData.FinalLevel)
            {
                case Level.TRACE: logger.LogTrace("{logMessage}", message); break;
                case Level.DEBUG: logger.LogDebug("{logMessage}", message); break;
                case Level.INFO: logger.LogInformation("{logMessage}", message); break;
                case Level.WARN: logger.LogWarning("{logMessage}", message); break;
                case Level.ERROR: logger.LogError("{logMessage}", message); break;
                case Level.FATAL: logger.LogCritical("{logMessage}", message); break;
            }`
since logger is an instance of type Microsoft.Extensions.Logging.ILogger, which exposed a method of the form
`LogXXX(string messageTemplate, params object[] args)`
the message template for ALL logs created by JSNLog will always be {logMessage}:
![image](https://user-images.githubusercontent.com/4141889/37525019-e8b31542-292b-11e8-89e1-1ea6129fdccb.png)
Therefore, I won't be able to search by message template in my log database, I'll have to search by regexp, which is what structured logging was invented to avoid.

In order to comply to structured logging patterns, I propose the following changes:
the JS methods should take a single parameter, of string or object type (or a function that returns such an object) with the following interface:
interface IStructuredLog {
    messageTemplate: string;
}
and then, for every property parsed from the template, a corresponding property, e.g.:
jsnlogger.LogDebug({ messageTemplate: "Hi from {User}", User: "User001" }).
On the server side, the LogDebug method should be passed the template and its properties, properly parsed.

**Comment by mperdeck** [comment]
Thanks for your suggestion. Sorry for the late reply.

My view of structured logging is a bit less specific than yours. To me, it allows you to access the individual fields inside the log item without having to first parse them. But to me it doesn't necessarily imply message strings with placeholders as you described.

You probably have already seen these structured logging related pages, but sending the links just in case:
http://jsnlog.com/Documentation/HowTo/StructuredLogging
http://jsnlog.com/Documentation/Configuration/JSNLog#serverSideMessageFormat

**Comment by yitzolsberg** [comment]
I think I've managed to acheive this without tons of modifications. It takes changing the Logger prototypes (in jsnlog.js) like so:
```js
Logger.prototype.trace = function (logObject, ...args) { return this.log(getTraceLevel(), logObject, undefined ,args); };
Logger.prototype.debug = function (logObject, ...args) { return this.log(getDebugLevel(), logObject, undefined, args); };
//... other levels
Logger.prototype.fatalException = function (logObject, e, ...args) { return this.log(getFatalLevel(), logObject, e, args); };
```
etc.
Then
```js
Logger.prototype.log = function (level, logObject, e, args) { //add args
// ...
   if (args && args.length) {
                      if (typeof logObject != "string")
                          throw new Error("Only use arguments with string only message")
                      excObject = {
                          "msg": logObject,
                          "arguments": args
                      };
                  }
    compositeMessage = stringifyLogObject(excObject); //etc
//...
```
And my logging adaptor now looks like this:
```csharp
public void Log(FinalLogData finalLogData)
{
    var logger = _loggerFactory.CreateLogger(finalLogData.FinalLogger);

    var logLevel = finalLogData.FinalLevel switch
    {
        Level.TRACE => LogLevel.Trace,
        Level.DEBUG => LogLevel.Debug,
        Level.INFO => LogLevel.Information,
        Level.WARN => LogLevel.Warning,
        Level.ERROR => LogLevel.Error,
        Level.FATAL => LogLevel.Critical,
        _ => LogLevel.None
    };

    if (logLevel == LogLevel.None)
        return;

    if (
       LogMessageHelpers.IsPotentialJson(finalLogData.FinalMessage)
       && TryParseJson<Structured>(finalLogData.FinalMessage, out var structured))
    {
        logger.Log(logLevel, structured.Msg, structured.Arguments);
    }
    else
    {
        logger.Log(logLevel, "{@logMessage}", finalLogData.FinalMessage);
    }
}
//https://stackoverflow.com/a/51428508/8170844
private static bool TryParseJson<T>(string str, out T result)
{
    bool success = true;
    var settings = new JsonSerializerSettings
    {
        Error = (sender, args) => { success = false; args.ErrorContext.Handled = true; },
        MissingMemberHandling = MissingMemberHandling.Error
    };
    result = JsonConvert.DeserializeObject<T>(str, settings);
    if (!success) result = default;
    return success;
}

private class Structured
{
    public string Msg { get; set; }
    public object[] Arguments { get; set; }
}
```

This doesn't change the public api of jsnlog.js, and allows calls like
`JL().warn("Position {@pos} complete in {ms}ms, {x: 10, y: 10}, 125);`
which logs through to serilog (or any `Microsoft.Extensions.LoggingILogger`) as expected.

I would put though a PR but it's two separate repos.

This can also be acheived without editing any existing code, the `ILoggingAdaptor` can be written and passed to `app.UseJSNLog` and the js code could be written as a facade-style service which wraps the arguments in an object as above. 

It seems you still need the [Destructurama.JsonNet](https://github.com/destructurama/json-net) to destructure the JObjects.

And many thanks @mperdeck for a wonderful library!
