### ISSUE TITLE
Is JSNLog asynchronous or synchronous?

### ISSUE THREAD

**Issue by dmitrynovik** [mperdeck/jsnlog#169]
This is more a question than an issue. The issue is that the documentation has no mention of it.

So, when I go and log anything - will it block on sending (sync) or not (async) - ?

I did my small digging into the code and it looks like it does `XMLHttpRequest.Send` which is asynchronous by default unless configured otherwise, but it would be nice to get the official confirmation.

Cheers,
Dmitry.

**Comment by mperdeck** [comment]
JSNLog is async. When you log something, it will never block. Also, there is no guarantee that after you've logged something, that something will make it to your server side log.
