### ISSUE TITLE
incomplete "m" json data in Internet Explorer 11

### ISSUE THREAD

**Issue by luoshiben** [mperdeck/jsnlog#171]
When an error is caught by the default onerror handler in Chrome, the "m" json attribute contains a json string with data structure like:
```
{"stack":"SyntaxError: Unexpected token .","message":"Unexpected token .","name":"SyntaxError","logData":{"msg":"Uncaught Exception","errorMsg":"Uncaught SyntaxError: Unexpected token .","url":"http://localhost:50002/","line number":35,"column":9}}
```

However, for the same error, the "m" json attribute contains a json string that only has the logData values. For example:
```
{"msg":"Uncaught Exception","errorMsg":"Script error","url":"https://code.jquery.com/jquery-3.3.1.min.js","line number":0,"column":0}
```

I believe that IE 11 does support onerror and provides stackTrace on the exception object. Why are the stack, message, and name values missing from the IE11 data that is collected and reports by jsnlog? Thanks for the help.

**Comment by mperdeck** [comment]
Your second code snippet shows a meaningless "Script error" message. I think the solution is here:
http://jsnlog.com/Documentation/HowTo/ObfuscatedScriptErrors
