### ISSUE TITLE
level does not exist on JL.setOptions()

### ISSUE THREAD

**Issue by MickL** [mperdeck/jsnlog#172]
As described [here](http://jsnlog.com/Documentation/JSNLogJs/AjaxAppender/SetOptions) the minimum level to log can be set. But the TypeScript interface `JSNLogOptions` does not `level`. Setting it anyway does not have any effect: If i set to 3000 it still logs 2000:

```
(<any>JL).setOptions({
      defaultAjaxUrl: environment.loggerUrl,
      level: 3000,
});

JL().debug('Should NOT be logged');
JL().info('Should be logged');
```

Version: 2.28.0

**Comment by mperdeck** [comment]
Looking at your code:
(<any>JL).setOptions({
      defaultAjaxUrl: environment.loggerUrl,
      level: 3000,
});

You are calling setOptions on JL, which represents the entire library:
http://jsnlog.com/Documentation/JSNLogJs/JL/SetOptions

The library itself has option _defaultAjaxUrl_, but not option _level_.

The _level_ option is used with loggers and appenders. So to set the level of  the root logger, you would write:
JL**()**.setOptions({
      level: 3000,
});

See
http://jsnlog.com/Documentation/JSNLogJs/Logger/SetOptions
