### ISSUE TITLE
Sending log requests to an ASP.Net controller action does not pass the exception

### ISSUE THREAD

**Issue by NewToJSNLoger** [mperdeck/jsnlog#175]
Hello there,
I am trying to explore JSNlog and see who it works asp.net (.Net Framework 4.6). Here is what I did, I followed the installation guide, so far so good, I updated the config file to override the defaultAjaxURL as follow:
<jsnlog productionLibraryPath="~/Scripts/jsnlog.min.js" defaultAjaxUrl="/Error/JSNLogger" enabled="true">
  </jsnlog>
and try to test. from a asp.net razor page I forced to throw an exception as in the attached, It calls the action properly but not able to handle the exception content, please see the attached.
any idea how to capture the exception would appreciated?
Thanks

![image](https://user-images.githubusercontent.com/42654703/44546770-f18c6900-a6e6-11e8-9703-30701164690e.png)

**Comment by mperdeck** [comment]
I understand that the log message does get sent to the server, but something goes wrong on the server, in your own code. I'm sorry, I can't help you with that.

This may be useful:
http://jsnlog.com/Documentation/HowTo/LogMessageFormat

Maybe by overriding the logging event, there is no need to create your own endpoiint:
http://jsnlog.com/Documentation/JavascriptLogging/OnLogging
