### ISSUE TITLE
Security Considerations

### ISSUE THREAD

**Issue by jonathh21** [mperdeck/jsnlog#177]
Hi all, I really wanted to use this package but I am concerned about the risk of dos via the logger.

Is there anyway to require the logging arrive via an autheticated connection for example?

Thanks..

**Comment by mperdeck** [comment]
Not out of the box. The server side JSNLog endpoint assumes that your web site is open to the public.

I can see these options:

1) You could create your own end point that receives the log messages. All it needs to do (in addition to authentication) is receive the JSON objects with log info from the browser, deserialize them and log them to your server side logging package.
http://jsnlog.com/Documentation/HowTo/LogMessageFormat

2) If you use OWIN or ASP.NET CORE, you could use a middleware component that authenticates incoming requests and place that in the pipeline before the JSNLog middleware.
