### ISSUE TITLE
Type 'ConsoleTransportInstance' is not assignable to type 'JSNLogAppender'.

### ISSUE THREAD

**Issue by vdepatla** [mperdeck/jsnlog#178]
Getting below error when I try to assign winston console transport as an appender. Any Idea ?
Type 'ConsoleTransportInstance' is not assignable to type 'JSNLogAppender'.
Property 'setOptions' is missing in type 'ConsoleTransportInstance'.

Code :
const consoleAppender = new winston.transports.Console({
json: false,
formatter: options => {
const logEntry: ClientSideLoggingResult = {
host: os.hostname(),
pid: process.pid,
level: options.level.toString(),
ts: moment().format(),
eventData: options.meta,
component: globalStrings.componentName
};
return JSON.stringify(logEntry);
}
});

    JL().setOptions({ appenders: [consoleAppender] });

**Comment by dmurvihill** [comment]
+1 similar issue. From the example [here](http://nodejs.jsnlog.com/Documentation/HowTo/LogToDb) it looks like we should be able to do something like this. Any advice?

**Comment by mperdeck** [comment]
Thanks for the heads up. A fix for this has now been released as part of version 2.29.0.
