### ISSUE TITLE
Documentation - Bad link to ILoggingAdapter example

### ISSUE THREAD

**Issue by rocknet** [mperdeck/jsnlog#182]
[This page ](http://jsnlog.com/Documentation/JavascriptLogging/SetJsnlogConfiguration) under the `ILoggingAdapter` section has a bad link to an example.  https://github.com/mperdeck/jsnlog/blob/master/JSNLog/LogHandling/CommonLoggingAdapter.cs

Two most likely candidates:
https://github.com/mperdeck/jsnlog/blob/master/jsnlog/LogHandling/AspNet4/CommonLoggingAdapter.cs
https://github.com/mperdeck/jsnlog/blob/master/jsnlog/PublicFacing/AspNet5/Configuration/LoggingAdapter.cs

**Comment by mperdeck** [comment]
Thanks for letting me know. I will fix this with the next release.
