### ISSUE TITLE
Log4j Vulnerability

### ISSUE THREAD

**Issue by JimmyTT** [mperdeck/jsnlog#195]
Hello, I've been reading up on the log4j vulnerability and use this package in my work. 

This package is listed as a port for log4j, is this package vulnerable?

**Comment by mperdeck** [comment]
No, it is not vulnerable.

It does not use Log4J, which is a Java package. There is a .Net version of that package, Log4Net. The main JSNLog package does not use Log4Net either. However, if you use Log4Net in your own code and your code uses the .Net Framework (not .Net Core), you may be using the JSNLog.Log4Net adapter package. This does have a dependency on Log4Net.
