### ISSUE TITLE
Wrong Common.Logging version for JSNLog.Log4Net

### ISSUE THREAD

**Issue by timorris** [mperdeck/jsnlog#40]
I've installed JSNLog.Log4Net version 2.7.2, which supposedly has a dependency on Common.Logging version >= 2.2.0, which is the version of Common.Logging I have installed.  However, when I try to use JSNLog, I get the following runtime error:

Could not load file or assembly 'Common.Logging, Version=2.1.2.0, Culture=neutral, PublicKeyToken=af08829b84f0328e' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Any thoughts?

**Comment by mooglegiant** [comment]
My issue was that I had an older copy of log4net in my bin folder in the mvc project, and nuget was not replacing the dll, it would download it to the packages folder and say it's installed, but not actually replace it.
