### ISSUE TITLE
Buffered log entries to be logged as one log entry

### ISSUE THREAD

**Issue by searope** [mperdeck/jsnlog#51]
Hello,
thanks for the great library! 
I see that the buffered log entries are sent to server as a bunch and saved to log as independent entries. It could be better to save these as one entry (or have an option to do it). It's especially useful if .NET logger (serilog in my case) is set to log only errors which would filter out all the buffered entries lower than error. But I think the idea of buffered messages is most useful in the scenario when I'd add debug/trace entries which will be only sent when an error happens.

**Comment by mperdeck** [comment]
Hello,

Thanks for the kind words!

The jsnlog element in your web.config has an attribute serverSideLevel. This allows you to override the level of the log messages received from the client.
http://jsnlog.com/Documentation/WebConfig/JSNLog

You could try setting that to Error. All log messages from the client (including Trace messages) would then be passed to Serilog with level Error. I guess this will get Serilog to log them.

Please let me know how you go with this.

Matt

**Comment by searope** [comment]
Thanks, it works.
