### ISSUE TITLE
Buffered log entries could be logged in wrong order with other entries

### ISSUE THREAD

**Issue by searope** [mperdeck/jsnlog#52]
if I have a buffered entries sent and if there are some other entries with high enough level to be sent  on their own immediately after, the entries can be logged in wrong order. I can see the calls to /jsnlog.logger are made in right order, but in the log file entries are not.
Looks like since there are more than one entry in the request payload, processing it on server end takes a bit longer than the queries which has only one entry even though they were sent a bit after.
To confirm the theory, I've added a 1 sec delay to the entries made after the buffered one and all was logged as expected.

**Comment by mperdeck** [comment]
All log messages have a timestamp, which is generated when the log message is created (not when it is sent).

Did you try solving the problem by sorting your logs by timestamp?

Also, this may be of use:
http://jsnlog.com/Documentation/GetStartedLogging/RequestIds

**Comment by searope** [comment]
The timestamp is created by SeriLog as I understand it. So it's always in the same order as entries in the log file. Sent timestamp using serverSideMessageFormat has the time in correct order since it's client's clock. So I could use this as a work-around. 
RequestId is not helping either since it's different for every request. The buffered entries and the ones sent on their own have the different RequestIds.

**Comment by mperdeck** [comment]
You wrote:
Sent timestamp using serverSideMessageFormat has the time in correct order since it's client's clock. So I could use this as a work-around. 

Sounds to me the problem was solved then. Closing this issue.
