### ISSUE TITLE
Discussion : Persistent & Offline support ?

### ISSUE THREAD

**Issue by fcamblor** [mperdeck/jsnlog#53]
Hi !

I'm currently needing some clientside logging allowing :
- to persist logs somewhere (in localstorage, for instance), in order to be able to "unleash" them when needed (for instance, only when an error occurs, in order to not pollute/load server logging if I have lots of clients)
- to bufferize logs on a rolling out manner, while not "unleashed" (because localstorage has limited size, I'd like, for instance, to limit to 1MB the persisted logs and roll out changes)
- to delay ajax call if client is offline

I never used jsnlog yet, but it seems configurable enough to make most of my requirements possible.

Would you agree ?
If you find those feature interesting, I may implement them an provide a PR with them if you help me a bit in implementing them :-)

Cheers,

**Comment by mperdeck** [comment]
I guess that JSNLog can already do some of what you're after. JSNLog is already able to store log messages in memory (not localstorage) and only send them if a high severity message is sent. See storeInBufferLevel, sendWithBufferLevel, bufferSize at
http://jsnlog.com/Documentation/WebConfig/JSNLog/AjaxAppender

Your changes would be in the jsnlog.js library (the JSNLog component that sits on the client). It isn't very complicated and all the less than trivial bits are heavily documented - if it can do what you're after, it probably won't be very hard for you to do it.

Exposure for JSNLog is always welcome :-)
