### ISSUE TITLE
XMLHttpRequest cannot load http://localhost/api/log. Request header field JSNLog-RequestId is not allowed by Access-Control-Allow-Headers.

### ISSUE THREAD

**Issue by adakumar** [mperdeck/jsnlog#54]
Hi All,

I am using the below code in my project but getting the below error.

Error: XMLHttpRequest cannot load http://localhost/api/log. Request header field JSNLog-RequestId is not allowed by Access-Control-Allow-Headers.

Code:

window.onerror = function( msg, url, lineNo,errorObj) 
    { 
		 JL("onerrorLogger").fatalException({
        "msg": "Exception!", 
        "errorMsg": msg, "url": url, 
        "line number": lineNo
		}, errorObj);
		
		 
        // return true to stop error from propogating, false to allow propogation
        return true; 
    };

var appender = JL.createAjaxAppender("appender");
		var consoleAppender=JL.createConsoleAppender('consoleAppender');
		appender.setOptions({"url": "http://localhost/api/log"
		});
		JL().setOptions({"requestId":"35F7446D-86F1-47FA-A9EC-547FFF510086","appenders": [appender]});
		
Could you please help me out to resolve this problem?

Thanks

**Comment by mperdeck** [comment]
It looks to me like you are trying to send the log messages to a different server than where your site is hosted. Access-Control-Allow-Headers is part of the CORS specification that enables this.

However, JSNLog doesn't support CORS at the moment.

This means if for example your site is hosted at http://abc.com, then the log messages have to go to http://abc.com as well. It would be simplest to leave the domain out of your url setting.

I am looking at supporting CORS, but this is non-trivial, and it is not a very common need.

**Comment by mperdeck** [comment]
JSNLog now supports CORS. See
http://jsnlog.com/Documentation/GetStartedLogging/CORS
