### ISSUE TITLE
disallowUserAgentRegex?

### ISSUE THREAD

**Issue by vorou** [mperdeck/jsnlog#56]
We don't support IE7, so I want to skip all the events from it. But it looks like there is no such thing as `disallowUserAgentRegex` in JSNLog.

Is there any way to do it, other than listing all the supported browsers in `userAgentRegex` or putting quite ugly [regex for "not contains"](http://stackoverflow.com/a/406408/1085375)?

**Comment by mperdeck** [comment]
Sorry, no there isn't. You'll have to go for one of the ways you described.
