### ISSUE TITLE
Modify Moessage Format

### ISSUE THREAD

**Issue by vivekp123** [mperdeck/jsnlog#57]
Is there a way to add new attribute in Log Message. I am looking to add more information to debug, info, warn, trace.

**Comment by vivekp123** [comment]
In The Log method below,

 Appender.prototype.log = function (level, msg, meta, callback, levelNbr, message, loggerName) {
            var logItem;
            if (!allow(this)) {
                return;
            }
            if (!allowMessage(this, message)) {
                return;
            }
            if (levelNbr < this.storeInBufferLevel) {
                // Ignore the log item completely
                return;
            }
            logItem = new LogItem(levelNbr, message, loggerName, (new Date).getTime());
            if (levelNbr < this.level) {
                // Store in the hold buffer. Do not send.
                if (this.bufferSize > 0) {
                    this.buffer.push(logItem);
                    // If we exceeded max buffer size, remove oldest item
                    if (this.buffer.length > this.bufferSize) {
                        this.buffer.shift();
                    }
                }
                return;
            }
            if (levelNbr < this.sendWithBufferLevel) {
                // Want to send the item, but not the contents of the buffer
                this.batchBuffer.push(logItem);
            }
            else {
                // Want to send both the item and the contents of the buffer.
                // Send contents of buffer first, because logically they happened first.
                if (this.buffer.length) {
                    this.batchBuffer = this.batchBuffer.concat(this.buffer);
                    this.buffer.length = 0;
                }
                this.batchBuffer.push(logItem);
            }
            if (this.batchBuffer.length >= this.batchSize) {
                this.sendBatch();
                return;
            }
        };


Can we have,

            logItem = new JL.LogItem(levelNbr, message, loggerName, (new Date).getTime());

So that, we can overwrite the log item and can add more parameters to it.

**Comment by mperdeck** [comment]
Hi Vivek,

I don't see the point of this. Seeing that the log message is created inside the jsnlog.js library, how would you set any new attributes? Why not log an object with any attributes you need?

A problem I see with opening up the log message format is that the server side component of for example the .Net version of JSNLog relies on the message format. If I open up that message format, people relying on the server side component could easily get into some strange situations.

Matt
