### ISSUE TITLE
Appender should define outputformat not the logger

### ISSUE THREAD

**Issue by fgieseke** [mperdeck/jsnlog#58]
In the current implementation the logger.log method expects the original message (logObject):
code: Logger.prototype.log = function (level, logObject, e) {
// then it creates a compositeMessage (string containing the stringify logObject)
code: compositeMessage = stringifyLogObject(excObject);
// then this compositeMessage is send to all the appenders
code: this.appenders[i].log(levelToString(level), compositeMessage.msg, compositeMessage.meta, function () {
                        }, level, compositeMessage.finalString, this.loggerName);

// but the original message (logObject) is lost.
}
Why is this bad? -> Separation of concerns!
The ajaxAppender requires (json)strings.
The consoleAppender maybe whats to output the logObject with console.dir. (for better representation)
A soapAppender would eventually need XML.

So it is the responsability of an appender to generate the output it needs.

I had to do some dirty hacks to output the original logObject in the consoleAppender.

**Comment by mperdeck** [comment]
I can see your point that it would be useful if appenders received the original log information, so they can optimize for their particular transport mechanism (ajax, browser console, soap, etc.)

On the other hand, this would make it more complicated to implement the logger options disallow and onceOnly
http://nodejs.jsnlog.com/Documentation/JSNLogJs/Logger/SetOptions

Also, I would then have to introduce a special appender to interface with Winston transports, while currently Winston transports can be used as JSNLog appenders.
http://nodejs.jsnlog.com/Documentation/GetStartedLogging/LogToDb

This can all be done of course. However, I have many things going on in my life besides JSNLog. I also try to keep modifications to a minimum to reduce the risk of breaking things, and I'm trying to keep jsnlog.js as simple and small as possible. 

Thanks for putting forward your suggestion. Although I can't see myself implementing this particular suggestion, I always welcome feedback and new ideas.

**Comment by fgieseke** [comment]
I could solve it putting the original logObject into the meta-object that's passed to the appender.
