### ISSUE TITLE
jsnlog.ts file won't compile (using VS2013 with AMD-modules)

### ISSUE THREAD

**Issue by fgieseke** [mperdeck/jsnlog#59]
The typescript representation of jsnlog isn't valid typescript.
JSNLogger doesn't implement the Interface.
- method "fatalException" is missing.

"JL" is defined as a function and a class at the same time.
Any reference to JL leads to an ambiguos reference-error...

Integration in a typescript Environment is tricky and I had to do some corrections in the type-Definition-file

**Comment by mperdeck** [comment]
Could you please send me a TypeScript snippet that reproduces the error.
Also, you said that you made some corrections in the type definition file. Could you send those to me please. That would be much appreciated.

**Comment by fgieseke** [comment]
I'm gave up, because in Typescript an Object "JL" can either be a function or a class. So I had to restructure the javascript "JL" in to a module with a static function JL but this means that I had to rewrite JavaScript-code. Maybe I will have time for that some day...
