### ISSUE TITLE
serverSideMessageFormat %url placeholder is replaced by wrong value (.NET)

### ISSUE THREAD

**Issue by VyacheslavPritykin** [mperdeck/jsnlog#61]
Hi,

From the documentation http://jsnlog.com/Documentation/WebConfig/JSNLog I see that the `%url` placeholder should be replaced by
>Url of the page on which the message was generated

However, currently it is replaced by the ajaxUrl, because there is the following code in `JSNLog.LoggerHandler.ProcessRequest`:

```C#
string url = context.Request.Url.AbsolutePath;
...
LoggerProcessor.ProcessLogRequest(json, userAgent, userHostAddress,
                serverSideTimeUtc, url, requestId);
```
Instead of

```C#
string url = (context.Request.UrlReferrer ?? context.Request.Url).AbsolutePath;
...
LoggerProcessor.ProcessLogRequest(json, userAgent, userHostAddress,
                serverSideTimeUtc, url, requestId);

**Comment by mperdeck** [comment]
Sorry for the very late response. I've implemented your change, which is now live.
