### ISSUE TITLE
Karma - Error: [$injector:unpr] Unknown provider: logToServerProvider <- logToServer

### ISSUE THREAD

**Issue by jguido66** [mperdeck/jsnlog#63]
I'm trying to write unit tests for my code and I get the unknown provider error message.  I've tried multiple ways to get this dependency included in my jasmine unit tests, but to no avail.  Do you have any examples of Karma/Jasmine unit tests that use JSNLog?

Joe

**Comment by mperdeck** [comment]
I'm sorry, no I don't.

**Comment by jguido66** [comment]
I solved the issue:

Here are my files "without prod code"

Karma.conf.js
<code>
// Karma configuration
// Generated on Tue Mar 03 2015 11:15:18 GMT-0500 (EST)

module.exports = function (config) {
    config.set({

        // base path that will be used to resolve all patterns (eg. files, exclude)
        basePath: '',


        // frameworks to use
        // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
        frameworks: ['jasmine'],


        // list of files / patterns to load in the browser
        files: [
            {pattern: 'modules/common/public/third/jquery/jquery.js', watch: false},
            {pattern: 'modules/common/public/third/angularjs/angular.js', watch: false},
			...
            {pattern: 'modules/common/public/third/jsnlog.min.js', watch: false},
            {pattern: 'modules/common/app/assets/js/common/model/log4Server.js', watch: false},
            'modules/campaigns/app/assets/js/**/*.js',
            'unit_test/**/*.test.js'
        ],

        // list of files to exclude
        exclude: ['target/**/*.js', '*/target/**/*.js', 'project/**/*.js'],

        // preprocess matching files before serving them to the browser
        // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
        preprocessors: {
            'modules/**/assets/js/**/*.js': ['coverage']
        },


        // test results reporter to use
        // possible values: 'dots', 'progress'
        // available reporters: https://npmjs.org/browse/keyword/karma-reporter
        // optionally, configure the reporter
        coverageReporter: {
            type: 'lcov',
            dir: 'coverage/',
            file: 'coverage.txt'
        },

        // test results reporter to use
        // possible values: 'dots', 'progress'
        // available reporters: https://npmjs.org/browse/keyword/karma-reporter
        reporters: ['progress', 'coverage'],


        // web server port
        port: 9876,


        // enable / disable colors in the output (reporters and logs)
        colors: true,


        // level of logging
        // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
        logLevel: config.LOG_INFO,


        // enable / disable watching file and executing tests whenever any file changes
        autoWatch: true,


        // start these browsers
        // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
        browsers: ['Chrome'],


        // Continuous Integration mode
        // if true, Karma captures browsers, runs the tests and exits
        singleRun: false
    });
};
</code>

logToServer.js
<code>
angular.module('logToServer', [])
    .service('$log', function () {
        this.log = function (msg) {
            JL('Angular').trace(msg);
        };
        this.debug = function (msg) {
            JL('Angular').debug(msg);
        };
        this.info = function (msg) {
            JL('Angular').info(msg);
        };
        this.warn = function (msg) {
            JL('Angular').warn(msg);
        };
        this.error = function (msg) {
            JL('Angular').error(msg);
        };
    });
</code>

angularFactory.js
<code>
var app = angular.module("myModule");

app.factory('$factory', ["$constants", "$timeout", "$translate", "$log", function ($constants, $timeout, $translate, $log) {

    //******************************************************************************
    //Private functions
    //******************************************************************************


    //******************************************************************************
    //Public functions
    //******************************************************************************
 
    function method() {
        returnValue = [];
        ...
        return returnValue;
    }

    return {
        method: method
    };
}]);
</code>

factoryUnitTest.js
<code>
'use strict';

describe('Module', function () {
    beforeEach(module('myModule'));

    var translationMock = {
        'FOO': 'bar',
		'BAR': 'foo'
    };

    beforeEach(module('pascalprecht.translate', function ($translateProvider) {
        $translateProvider
            .translations('en', translationMock)
            .translations('en', {
                'FOO': 'bar',
                'BAR': 'foo'
            })
            .preferredLanguage('en');
    }));

    var factory, $log;
    var successMockResponse = [
        {
            id: 1,
			active: false,
            version: 1
        },
        {
            id: 2,
            active: true,
            version: 1
        },
        {
            id: 3,
            active: true,
            version: 1
        }
    ];

    beforeEach(inject(function () {
        // The injector unwraps the underscores (_) from around the parameter names when matching
        inject(function ($injector) {
            factory = $injector.get('$factory');
            $log = $injector.get('$log');
        });
    }));

    describe("error trying to add a record from an invalid server response", function () {
        var successResponse = [];

        beforeEach(function () {
            angular.copy(successMockResponse, successResponse);
        });

        function _method(mockResponse) {
            var error, camp, campaign;
            try {
                for (campaign in mockResponse) {
                    camp = mockResponse[campaign];
                    factory.method(camp);
                }
            } catch (e) {
                error = e;
            }
            return error;
        }

        it('should log and throw an error when the response contains an invalid campaign id value', function () {
            successResponse[0].id = undefined;
            var error = _method(successResponse);
            expect(error).toEqual('Module - id: undefined');
        });
    });
});
</code>
