### ISSUE TITLE
pass json object to web api

### ISSUE THREAD

**Issue by bigerock** [mperdeck/jsnlog#64]
is there any way to pass the json object to a web api instead of using nlog, etc?

meaning, i want to pass the json to a web api controller/method like this:

    public class ErrorLoggerController : ApiController
    {
        // POST: api/ErrorLogger
        public void Post(Error error){
            //log something to a db here
        }
    }

where in the above example the Error class is some custom class that gets serialized from JSON

**Comment by mperdeck** [comment]
Yes, you can.

1) You can tell JSNLog what url to send its log requests to, either per AjaxAppender, or globally:
http://jsnlog.com/Documentation/WebConfig/JSNLog - see  defaultAjaxUrl
http://jsnlog.com/Documentation/WebConfig/JSNLog/AjaxAppender - see url

2) You will want to make sure that your Error object has the same fields as the JSON objects sent by JSNLog:
http://js.jsnlog.com/Documentation/DownloadInstall - See "Format of the log messages"

The server side bit of JSNLog pretty much does what you want to do. It is not written as an Web API though. See:
https://github.com/mperdeck/jsnlog/blob/master/JSNLog/LogHandling/LoggerHandler.cs
https://github.com/mperdeck/jsnlog
