### ISSUE TITLE
Modify Console Format/Layout

### ISSUE THREAD

**Issue by ShaneCourtrille** [mperdeck/jsnlog#65]
Is there any support for changing the format/layout for the console appender? Rather then..

loggerName: message

I want to see...

[loggerName] : message

**Comment by mperdeck** [comment]
No, there isn't. It's all hard coded in jsnlog.js to keep things simple and as small as possible.

If you're interested, the message sent to the console is created in
https://github.com/mperdeck/jsnlog.js/blob/master/jsnlog.js
just below the line
ConsoleAppender.prototype.sendLogItemsConsole = function (logItems) {
