### ISSUE TITLE
How to get JSNLog to work with .net framework 3.5?

### ISSUE THREAD

**Issue by saishree** [mperdeck/jsnlog#66]
There is no place that lists the compatibility of jsnlog with different .net versions.
Could you direct me towards any such location or rather state whether JSNLog is indeed compatible with .net framework 3.5.

**Comment by mperdeck** [comment]
Apologies for the late response.

I don't know whether JSNLog works with .Net 3.5. 
3.5 was superceded by .Net 4 back in 2010, well before JSNLog's first release, so the answer may well be no.
