### ISSUE TITLE
NullReferenceException when running on ASP.NET 5 MVC 6

### ISSUE THREAD

**Issue by jltrem** [mperdeck/jsnlog#68]
```
System.NullReferenceException
Object reference not set to an instance of an object.
at JSNLog.Infrastructure.ConfigProcessor.ProcessRoot(XmlElement xe, String requestId, StringBuilder sb) 
at JSNLog.JavascriptLogging.Configure(String requestId) 
```

Is there a fork where somebody is working on supporting ASP.NET vNext?

**Comment by mperdeck** [comment]
Apologies for the late reply. I don't know if somebody is working on a version that supports vNext. I've looked into this and it requires quite a bit of refactoring. I still want to do this, but there is no ETA.

About the specific exception you saw - do you have a small MVC 6 program that reproduces the issue? That would make it easier for me to fix the issue when I have time (I'll be flat out with other things for at least the next 6 weeks).

**Comment by jltrem** [comment]
@mperdeck No problem.  ASP.NET 5 is still in flux but I'm in the thick of it now.  Within a few weeks I should be able to look into this issue and fix it.

**Comment by jltrem** [comment]
You are right, the JSNLog (C#) project will require some work to decouple it from `System.Web` and `HttpContext`.   I made a simple project showing the error when using JSNlog, but then continued to get jsnlog.js working with the project using NLog directly.  The project is [jsnlog.nlog.sample.vs2015](https://github.com/jltrem/jsnlog.nlog.sample.vs2015), and the readme points out the significant parts of using the two together.
