### ISSUE TITLE
Setting the Title field in Ent lib log

### ISSUE THREAD

**Issue by DarrinRobertson** [mperdeck/jsnlog#71]
Hi
I am logging my JSNlog data to the Ent Lib 5 logging database via the Common.logger EntLib50 adapter.
Currently the Title column is blank. Is there a way to specify what the title column in the database should be?

**Comment by mperdeck** [comment]
Hi Darrin,

Apologies for the late reply. I'm sorry, I've never used Ent Lib 5 and I can't answer your question. You might want to have a look at the source code of the EntLib50 adapter.

Matt
