### ISSUE TITLE
Serilog bridge not mapping objects

### ISSUE THREAD

**Issue by canoas** [mperdeck/jsnlog#72]
```
 JL().debug({msg: "message {x}", "x":2});
```
if we send a log message using an object (name + values in Json), these get to serilog/seq as a json message as a string

```
message: {msg: "message {x}", x: 2} 
```

where could we control this mapping to allow a proper serilog message like:

```
message: "message 2"
messageTemplate: "message {x}"
properties: {
    x: 2
}
```

Any idea where to start?

**Comment by mperdeck** [comment]
My approach would be to create your own version of the Serilog Common.Logging adapter.

JSNLog itself isn't aware that you're using Serilog (or NLog or Log4Net, etc.) It passes the string that you're seeing to the adapter.  It is up to the adapter to pass that string to the database.

Your version of the adapter could deserialize the JSON object and then call Serilog the way you want.

The adapter that is included in the JSNLog.Serilog NuGet package is here:
https://github.com/mperdeck/Common.Logging.Serilog.StructuredText
One option would be to fork this and create your own version.

You may also want to have a look at the serverSideMessageFormat section in
http://jsnlog.com/Documentation/WebConfig/JSNLog
