### ISSUE TITLE
Cyclic structures

### ISSUE THREAD

**Issue by mdeweerd** [mperdeck/jsnlog#73]
Hi

I added JSNLog to my Yii Framework setup as an extension in order to catch some unreported JavaScript issues.  I plan to publish this extension as soon as it has matured a bit in my environment.

I have got one where JSNLog reports kind of on itself:
{"msg":"Exception!","errorMsg":"TypeError: JSON.stringify cannot serialize cyclic structures.","url":"[...]/jsnlog.min.js","line
number":4,"column":432}

Now, I am confident that the issue comes from the data that is trying to be reported, but it would be nice to have some of the JSON data being reported even if it is cyclic.

Thanks for considering

Mario DW

**Comment by sinasalek** [comment]
Experiencing the same problem. 
closed as duplicate of this issue https://github.com/mperdeck/jsnlog/issues/113

**Comment by mdeweerd** [comment]
For information to those that encounter the same issue.
I have been using this for a while and as I have completely forgotten about this issue, I suppose that it works ;-):

Using: https://github.com/Canop/JSON.prune/blob/master/JSON.prune.js

Added:
`window.onerror = function (errorMsg, url, lineNumber, column, errorObj) {
    JL("onerrorLogger").fatalException({
        "msg": "Exception!",
        "errorMsg": errorMsg, "url": url,
        "line number": lineNumber, "column": column
    }, JSON.pruned(errorObj));

    // Tell browser to run its own error handler as well
    return false;
}`

**Comment by mperdeck** [comment]
As the error message indicates, it seems that it is JSON.stringify that raises the error. I'm trying very hard to keep jsnlog.js small and simple, so relying on for example JSON.stringify rather than implementing my own (slightly better) code.

Thanks for the tip about JSON.pruned. I'll add it to the documentation next time I work on it.

**Comment by mperdeck** [comment]
@mdeweerd I'm honoured that you decided to use JSNLog in the Yii framework. Is it ok if I put the Yii logo (plus link back to the Yii site) at the bottom of the jsnlog.com web site? Also, can I tweet about it?

**Comment by mdeweerd** [comment]
Hi
I am not an official Yii spokesman, but I have seen others do it so I do not think that you should hesitate.

Because of your question, I have uploaded my implementation for Yii 1.1 here: http://www.yiiframework.com/extension/yjsnlog/ .

**Comment by sinasalek** [comment]
Since the whole purpose of jsnlog is to report errors i think traversing the data and correct it before converting it to JSON is more practical way of solving this issue. for example if it's an DOM element, we can use innerHTML to convert it to HTML.
http://stackoverflow.com/questions/11616630/json-stringify-avoid-typeerror-converting-circular-structure-to-json
http://stackoverflow.com/questions/10392293/stringify-convert-to-json-a-javascript-object-with-circular-reference

I like this one, very short code:
https://github.com/isaacs/json-stringify-safe/blob/master/stringify.js

**Comment by mdeweerd** [comment]
Very old ticket - no longer expecting this to be implemented.

**Comment by mperdeck** [comment]
For a way to deal with cyclic structures, see:
http://jsnlog.com/Documentation/HowTo/CyclicReferences

**Comment by mdeweerd** [comment]
Personally I am using the suggestion from @sinasalek for some time now in stead of prune.
Works fine and it is much shorter than cyclic.js.

It's just this (code from stringify.js referenced above):
```
window.ystringify=function(obj, replacer, spaces, cycleReplacer) {
  return JSON.stringify(obj, serializer(replacer, cycleReplacer), spaces)
}
window.serializer=function(replacer, cycleReplacer) {
  var stack = [], keys = []

  if (cycleReplacer == null) cycleReplacer = function(key, value) {
    if (stack[0] === value) return "[Circular ~]"
    return "[Circular ~." + keys.slice(0, stack.indexOf(value)).join(".") + "]"
  }

  return function(key, value) {
    if (stack.length > 0) {
      var thisPos = stack.indexOf(this)
      ~thisPos ? stack.splice(thisPos + 1) : stack.push(this)
      ~thisPos ? keys.splice(thisPos, Infinity, key) : keys.push(key)
      if (~stack.indexOf(value)) value = cycleReplacer.call(this, key, value)
    }
    else stack.push(value)

    return replacer == null ? value : replacer.call(this, key, value)
  }
};

window.onerror = function (errorMsg, url, lineNumber, column, errorObj) {
    JL("onerrorLogger").fatalException({
        "msg": "Exception!",
        "errorMsg": errorMsg, "url": url,
        "line number": lineNumber, "column": column
    }, window.ystringify(errorObj));

    // Tell browser to run its own error handler as well
    return false;
}
```
