### ISSUE TITLE
Angular with MVC and jsnlog

### ISSUE THREAD

**Issue by dealkk** [mperdeck/jsnlog#75]
I have angularjs jsnlog on client with instuction on jsnlog.com,but want to use jsnlog on server that control setting/options. i follow instruction to add jsnlog form nuget and this tag
 @Html.Raw(JSNLog.JavascriptLogging.Configure())

i got an error
 Uncaught TypeError: Cannot read property 'setOptions' of undefined

**Comment by mperdeck** [comment]
Apologies for the late reply.

I can't reproduce this from your description. If this is still happening, could you post some working code on the github that reproduces the problem.
