### ISSUE TITLE
JSNLog and NancyFx

### ISSUE THREAD

**Issue by AlanGRutter** [mperdeck/jsnlog#76]
I have an Angular project that uses NancyFx and the Super Simple View Engine (SSVE). I am trying to configure JSNLog but I can't figure it out.

I've installed JSNLog NUget for Common.Logging. I don't know how to put the JSNLog.JavascriptLogging.Configure into my master.sshtl file. It just does nothing.

I'm also not sure about the JSNLogConfig.cs file that was included in App_Start. What's this for - I'm not using MVC. 

Is it possible to use JSNLog with Nancy?

**Comment by tparnell8** [comment]
Just do the jsnlogconfig stuff in the nancy bootstrapper

**Comment by mperdeck** [comment]
I have no experience with NancyFx or SSVE, so can't help you there.
