### ISSUE TITLE
Windows authentication

### ISSUE THREAD

**Issue by PeteA52** [mperdeck/jsnlog#77]
Is it possible to use JSNLog in an MVC site that uses Windows Authentication? I am getting 401 responses to all JSNLog requests.

Thanks,
Pete

**Comment by mperdeck** [comment]
Apologies for the late reply.

I haven't tested JSNLog on a site that uses Windows Authentication, so can't answer your question directly.

Maybe a solution is to configure your site, so the .logger end point is not in the private area of your site.
