### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by ashwin027** [mperdeck/jsnlog#85]
Hello!
I'm using typescript in one of my projects and I'm trying to integrate jsnlog but I'm unable to find the type definitions. I downloaded the zipped file, extracted it and searched for the definitions and only the jquery definitions showed up. Can you please include the type definitions?

It would be awesome if we can include this in the defintelytyped respository and get it into nuget.

https://github.com/DefinitelyTyped/DefinitelyTyped

Thanks for a fantastic library! :)

**Comment by mperdeck** [comment]
The typescript definitions are in the jsnlog.js project, at
https://github.com/mperdeck/jsnlog.js/blob/master/jsnlog_interfaces.d.ts
https://github.com/mperdeck/jsnlog.js/blob/master/jsnlog.d.ts

Getting it onto DefinitelyTyped is a good idea. I'll send them a pull request.
