### ISSUE TITLE
Owin

### ISSUE THREAD

**Issue by Scratchbuild52** [mperdeck/jsnlog#86]
Hi there,

Can I use this on versions of Owin bigger than 2.1? 
We are already on version 5.
If I can how do I do it, because Nuget fails when I try to install it.

Regards

Nic Scheepers

**Comment by mperdeck** [comment]
Hi Nic,

Thanks for your feedback. I found there was a bug in the JSNLog package definition causing the problem you saw.

I have now released version 2.12.1 which has this fixed. Please give it another try.

Matt
