### ISSUE TITLE
onceOnly without a regexp

### ISSUE THREAD

**Issue by JanisE** [mperdeck/jsnlog#88]
Hello!

I would like to suggest the option "onceOnly" to have a simple form of taking no arguments and discarding all messages that are exactly the same (the same error message, the same backtrace).

**Comment by mperdeck** [comment]
The onceOnly form with no arguments already exists. When that is used, it cancels the onceOnly of the parent logger. See very bottom of
http://jsnlog.com/Documentation/Configuration/JSNLog/Logger

I get what you're saying about having a way to suppress all exact duplicates (without matching regular expressions). That would be a useful feature. Maybe a boolean flag on the logger "suppressAllDuplicates" or something like that.

I won't have much time until the beginning of January. But after that, if you want to implement this feature and send me a pull request, that would be awesome.
