### ISSUE TITLE
un able to install in my project via nuget.

### ISSUE THREAD

**Issue by Kaushik1987** [mperdeck/jsnlog#89]
It's giving me following error.. 

Install-Package : Unable to resolve dependency 'JSNLog (≥ 2.15.0)'.
At line:1 char:1
+ Install-Package JSNLog.Elmah
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

is there any other way via i can use with Elmah ?

**Comment by mperdeck** [comment]
There was an issue during the release of JSNLog version 2.15.0, causing it to get out of sync with the other packages.  That's now fixed. Please try again.
