### ISSUE TITLE
Log level conversion to Serilog is incorrect

### ISSUE THREAD

**Issue by kbettenhausen** [mperdeck/jsnlog#90]
I'm seeing issues when logging using serilog. Debugs are logged fine but infos are logged as warnings and none of the other levels are logged at all. After digging into the source code for common.logging and serilog it looks like the log level enums are off. In the "Common.Logging.Serilog.StructuredText" project there is a function that looks like this:

```
private LogEventLevel ConvertLevel(LogLevel logLevel)
        {
            LogEventLevel logEventLevel;
            if (!Enum.TryParse(logLevel.ToString(), true, out logEventLevel))
            {
                switch (logLevel)
                {
                    case LogLevel.All:
                        logEventLevel = LogEventLevel.Verbose;
                        break;
                    case LogLevel.Info:
                        logEventLevel = LogEventLevel.Information;
                        break;
                    case LogLevel.Warn:
                        logEventLevel = LogEventLevel.Warning;
                        break;
                }
            }

            return logEventLevel;
        }
```

The common.logging log level enum looks like so:
```
[Flags]
    public enum LogLevel
    {
        All = 0,
        Trace = 1,
        Debug = 2,
        Info = 4,
        Warn = 8,
        Error = 16,
        Fatal = 32,
        Off = 64,
    }
```

and the serilog log level enum looks like:
```
public enum LogEventLevel
    {
        Verbose,
        Debug,
        Information,
        Warning,
        Error,
        Fatal
    }
```

The enum indexes don't line up and I think that is what is preventing most levels from getting logged or getting logged incorrectly.

**Comment by mperdeck** [comment]
Sorry for the late reply. I've released a new version of the package that hopefully solves those issues.

**Comment by kbettenhausen** [comment]
It is better but I think this line is still messing up the info logs:

```
if (!Enum.TryParse(logLevel.ToString(), true, out logEventLevel))
```

Since in Common.Logging the "Info" logging has an index of 4 it will map to Serilog's "Warning". 
It seems like explicitly setting the log level in the switch without the if statement may work.

**Comment by jimmymain** [comment]
I am using JSNLog.Serilog version 2.17.4, and am experiencing the same problem. When I log information level events in JSNLog they appear in Serilog as warnings.

**Comment by mperdeck** [comment]
I finally figured out why this was happening and fixed it in the latest release.
If you upgrade JSNLog.Serilog to version 2.17.5, that should pull in the latest version of Common.Logging.Serilog.StructuredText (1.0.5) which fixes the problem.
