### ISSUE TITLE
405 error

### ISSUE THREAD

**Issue by roialga** [mperdeck/jsnlog#91]
Hello,

When I try to use the jsnlog only JS. I get 405 error on the post method. Although there is allot of web information on this subject I wasn't successful In making the jsnlog to work. I am with iis 7. Any ideas? 

thanks, Roi.

**Comment by mperdeck** [comment]
I don't know how you set up your server, etc., so I can only speculate.

The only scenario I can think of right now is this:

* Your log requests are cross domain (your site is at domain x.com, and you got JSNLog to send the log requests to domain y.com)
See http://jsnlog.com/Documentation/HowTo/CORS

* In this case, JSNLog uses the CORS protocol. The CORS protocol involves sending an OPTIONS request (OPTIONS is a verb, just as GET and POST)

* You would see a 405 if your server does not allow OPTIONS requests.

If that sounds like what might be happening at your end, please do a bit of googling to find out how to get IIS 7 to accept OPTIONS requests.

If I'm on the wrong track, could you please create a very simple application that reproduces the situation and put it on github. That way, I can reproduce the problem at my end and fix it.

Let me know how you go.

**Comment by roialga** [comment]
Hello,
It's not a cross domain issue. The app is in the same folder of the jsnlog.js and the jsnlog.logger files.
I sure as well that the problem is on my side. I have tried allowing verb in some of the handlers (after allot of google) but I got the same error. I am adding 2 pictures one for the folder itself and one of the console.  I even tried to find which handler Handel this specific request but failed. 

the webapp url (public):
http://gis.mokedteva.co.il/opendata/log/

![consloeerror](https://cloud.githubusercontent.com/assets/16536878/12165883/3193994e-b52a-11e5-97eb-4b4a5629fbc0.JPG)
![logfolder](https://cloud.githubusercontent.com/assets/16536878/12165886/33323562-b52a-11e5-9ef0-820afd6166e0.JPG)

**Comment by mperdeck** [comment]
Looking at your directory listing, you have a static file jsnlog.logger

It seems jsnlog.js is trying to do a POST to /jsnlog.logger (as expected), but then IIS sees the static file and thinks it is trying to do a POST to the static file. This is normally not allowed, resulting in a 405.

JSNLog uses its own HTTP Handler to receive log requests. Your web.config needs to have a bit of configuration that directs all requests for jsnlog.logger to that handler.

If you create a new empty MVC project and install one of these Nuget packages, you'll find that the Nuget package automatically adds the required configuration to your web.config:

JSNLog.Log4Net
JSNLog.NLog
JSNLog.Elmah
JSNLog.Serilog

To get JSNLog installed in your application, you could try getting rid of all the JSNLog changes you made so far to your project, and then installing one of the above Nuget packages. That is the easiest way to install JSNLog. Also try getting rid of the static file jsnlog.logger. JSNLog does not expect it to be there.

You'll find working examples of simple sites that use JSNLog in
https://github.com/mperdeck/jsnlogSimpleWorkingDemos

**Comment by roialga** [comment]
Hello,
As I am not a .net developer and I was hoping to use only the "JS Only" part. Is there any way do advance only with JS or I should put my afford in your latest answer?
thanks allot,
Roi.

**Comment by Pumpapa** [comment]
I reply since your CORS-oriented solution seems to fit me.

I've been trying to get JSNlog to work for several hours. I have a JavaScript/JQuery client and a simple node.js server (in another domain).

The client seems to refuse to send any url other than the default **`http://localhost/jsnlog.logger.`**
Currently the client-side initialisation looks like:
` JL().setOptions({ "defaultAjaxUrl": <myServerURLhere> })`
but in fact doesn't do what I expected. It ends up in Logger.prototype.setOptions (below) which doesn't look at defaultAjaxUrl.
```
        Logger.prototype.setOptions = function (options) {
            copyProperty("level", options, this);
            copyProperty("userAgentRegex", options, this);
            copyProperty("disallow", options, this);
            copyProperty("ipRegex", options, this);
            copyProperty("appenders", options, this);
            copyProperty("onceOnly", options, this);

            // Reset seenRegexes, in case onceOnly has been changed.
            this.seenRegexes = [];

            return this;
        };
```

The actual error handler is pretty much the default:
```
window.onerror = function (errorMsg, url, lineNumber, column, errorObj) {
    JL().fatalException({
        "msg": "Exception!", 
        "errorMsg": errorMsg, 
        "url": <myServerURLhere>, 
        "line number": lineNumber, "column": column
    }, errorObj);

    return false;
}
```
Only when I hardwire my URL into `AjaxAppender.prototype.sendLogItemsAjax` does it get used.

Then my browser complains `XMLHttpRequest cannot load http://192.168.0.125:8083/my.logger. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access. The response had HTTP status code 405.` even though I've set `corsAllowedOriginsRegex` with what should be an appropriate regexp: `JL.setOptions({corsAllowedOriginsRegex:"^https?\:\\/\\/([a-z0-9]+[.])*(publistat[.]nl|192.168.0.125|localhost)$"})` (in node.js)

After fiddling in node.js, my last attempt gave:
`XMLHttpRequest cannot load http://192.168.0.125:8083/my.logger. Request header field JSNLog-RequestId is not allowed by Access-Control-Allow-Headers in preflight response.`

So apparently the OPTIONS message is now arriving, but something still goes wrong.

Suggestions?

**Comment by mperdeck** [comment]
@Pumpapa 

**About setting defaultAjaxUrl**

I understand that you wrote this JavaScript:
JL().setOptions({ "defaultAjaxUrl": <myServerURLhere> })

This tries to set the defaultAjaxUrl option on the nameless logger.
However, defaultAjaxUrl is not a logger option. It is an option on the library as a whole.
You could set defaultAjaxUrl on the library like so:

JL.setOptions({
    "defaultAjaxUrl": "..."
});

Note no () after the JL. See
http://nodejs.jsnlog.com/Documentation/JSNLogJs/JL/SetOptions

**About the CORS issues**
I saw you attempted to set corsAllowedOriginsRegex on the JL library. However, this tells the server (not the client) what domains to allow. Only the .Net edition of JSNLog uses this setting - to configure the .Net server side end point.

It seems to me that right now the sticking point is that CORS on your server does not allow the header JSNLog-RequestId. This is a custom header sent by the jsnlog.js client.

When your server sends its CORS preflight response to the OPTIONS request from the client, it needs to include a Access-Control-Allow-Headers header for JSNLog-RequestId, to tell the client that the server is happy to receive that header. For details, I found this page about CORS really enlightening (search that page for Access-Control-Allow-Headers):
http://www.html5rocks.com/en/tutorials/cors/

So the solution would be to configure nodejs to send the Access-Control-Allow-Headers header for JSNLog-RequestId in response to CORS preflight requests.

**Comment by Pumpapa** [comment]
Hey Matt,
thanks very much for looking into this. As soon as I have time I'll dive into this again.
Thanks!

**Comment by NewbieAngular** [comment]
Mine is an angular 4 app and here is what I get : 

JL.setOptions({
  "defaultAjaxUrl": '<my server url>' 
});

 I have two issues here .

1.  I see  like this :  

 OPTIONS http://localhost:8601/serverURI 0 () 
failed net :: ERR_CONNECTION_REFUSED

2 .  I would change the defaultAjaxUrl / url to any url at run time. how can I do that?
