### ISSUE TITLE
Issue in buffering logs while navigating in different MVC views 

### ISSUE THREAD

**Issue by amit4540** [mperdeck/jsnlog#94]
Am using JSN LOG with log4 net in MVC application.
i want to buffer my logs and send it to server only when there is a fatal exception, i am able to it on single page... (on a single view) but when i navigate to other view the buffer is lost, i guess new instance is getting created.. I want the buffer to remain intact throughout and send the log to server when ever any fatal exception occurs on any view.

**Comment by mperdeck** [comment]
You said
"when i navigate to other view the buffer is lost"

Do you mean the buffer is lost during a page refresh? 
You're right, that would indeed be the case.

I'm not sure though why keeping the buffer across page refreshes would be useful though.

**Comment by amit4540** [comment]
Thanks for the reply.

It was our requirement to store the logs in buffer while navigating between pages or refresh on same page, i was just trying to find if there is something already available from JSNLOG to do this.
Though i made some modifications in jsnlog.js file and wrote the logs to file using (page unload event) instead of storing them in buffer when any of above scenarios occur doing this i have the logs with me. It was just a workaround.

Any ways thanks for confirming that this is default behavior and nothing is available for this scenario.
