### ISSUE TITLE
Using JSNLog with TypeScript, SystemJS and JSPM

### ISSUE THREAD

**Issue by alexanderharm** [mperdeck/jsnlog#97]
I'm trying to use JSNLog in my project but would like to wrap the library in my own service. Following your documentation I'm trying to import JSNLog as follows:
```javascript
// documentation
var JL = require('jsnlog').JL
// which in TypeScript should be equivalent to
import {JL} from 'jsnlog'
```
While it seems to transpile OK it throws an error during runtime:
`TypeError: Cannot read property 'createConsoleAppender' of undefined`
or
`TypeError: JL.createConsoleAppender is not a function`
Am not sure if the problem lies with `JSNLog`, `SystemJS` or `JSPM`. Any ideas?

**Comment by mperdeck** [comment]
I'm sorry, I have no experience with SystemJS or JSPM.

You may want to compare your code with some working demo code that uses require. That might give some clues on what is going wrong:
https://github.com/mperdeck/jsnlog.NodeJsWorkingDemos
