### ISSUE TITLE
Different levels for console and ajax?

### ISSUE THREAD

**Issue by supertemp** [mperdeck/jsnlog#98]
Hi, can someone clarify for me, should the console and ajax appenders support different levels? I'm trying to log anything to the console but log fatals to the server. I'm getting some debugs through to the server with the following config (this is on an asp.net 4 webforms project using NLOG.

Thanks for any info.

```
<jsnlog enabled="true" productionLibraryPath="~/Scripts/jsnlog.min.js" serverSideLogger="jsn.logger">		
	<ajaxAppender name="ajaxAppender" level="WARN"/>
	<consoleAppender name="consoleAppender" level="ALL"/>
	<logger appenders="ajaxAppender;consoleAppender"/>
</jsnlog>
```

**Comment by mperdeck** [comment]
Yes, every appender has its own level. Only messages with severity equal or higher than that level will be processed by the appender.

Your definition sets the level of the ajax appender to WARN. The expected behaviour is that it will process all messages with severity WARN or higher - that is, it won't only process fatal messages.

**Comment by supertemp** [comment]
Thanks, that's what I understood. 

I'm getting debug messages through to the server, but only after the initial page load. To test, on the page load I am running
			JL("jsn.logger").trace("Trace");
			JL("jsn.logger").debug("Debug");
			JL("jsn.logger").warn("Warn");
			JL("jsn.logger").fatal("Fatal");

And only the warn and fatal is being sent to the server.

This project has signal r in it which is calling a client function that was console.logging to the client for info purposes only. I changed this function to use JL("jsn.logger").debug(msg), but these are being sent to the server via the ajax page, almost as if it is getting a new logger. I will try to track down what I have done wrong here or what is happening.
